### ISSUE TITLE
Wageningen Assistance

### ISSUE THREAD

**Issue by gtalckmin** [lcreteig/amsterdown#3]
Hello Leon,

I noticed that you recently published your thesis using RMarkdown + bookdown (thesis down).

I am finishing my thesis at Wageningen and keen to create a WURdown, as I have also worked on Rmarkdown for my individual chapters

We have a WUR thesis template available (template.tex and csl) 
https://github.com/bbrede/Wageningen_PhD_thesis_template 

I am struggling a bit on what should I alter on the master branch, to have this working with our template. 

Could you let me know if we can exchange some e-mails about this?

Cheers,
Gustavo

**Comment by LeonhardBakker** [comment]
Hi Gustavo,

Can you please send me your e-mail address? 

Kind regards, Leonhard

**Comment by gtalckmin** [comment]
Hi Leonhard,

Thanks for the quick response. My email is gustavo.alckmin@wur.nl.

Cheers,

Gustavo Togeiro de Alckmin




________________________________

**Comment by lcreteig** [comment]
Hi Gustavo,

Great that you're willing to make a version for your university! Note that besides the one I made there are [plenty of others](https://github.com/ismayc/thesisdown#customizing-thesisdown-to-your-institution), so do check those out for inspiration as well.

It's been a while since I looked at this, and I'm not too well-versed in LaTeX myself, but I'm happy to help. Seems to me that broadly you'll need to do the following:

The example thesis that `amsterdown` comes with is in [`inst/rmarkdown/templates/thesis/skeleton/`](https://github.com/lcreteig/amsterdown/tree/master/inst/rmarkdown/templates/thesis/skeleton). You'll need to add all of the relevant parts of the WUR template (`main.tex` in the repo you linked) to `template.tex` (or the other way around). Your best bet is to just go through the sections one by one, see where they overlap and where they differ, make incremental changes, and then try to compile the thesis to see if (how) it works.

`amsterdown` also offers a few YAML variables that users can set, so they don't have to mess with the LaTeX code in the template themselves (see [the docs](https://lcreteig.github.io/amsterdown/articles/amsterdown.html#title-pages)) . For instance, the `time` variable (for the time of your defense) is incorporated into [this line](https://github.com/lcreteig/amsterdown/blob/a92f3d1dd3ff0e5f31c455f48d94d6b097e97cb3/inst/rmarkdown/templates/thesis/skeleton/template.tex#L272) of `template.tex`. You'll probably also want to change these, depending on the WUR thesis requirements.

Finally, you'll need to translate all the example chapters of the WUR template (e.g. [`intro.tex`](https://github.com/bbrede/Wageningen_PhD_thesis_template/blob/master/01_intro.tex)) into RMarkdown, like the ones in `amsterdown`.

I realize this might be quite abstract, but I hope this helps a bit. If you need some more help with concrete issues, feel free to contact me still.

Good luck!
